---
title: "JOURN 8016: Adv. Quant. Research Methods"
subtitle: "Day 1"
author: "Michael W. Kearney📊<br/>School of Journalism <br/>Informatics Institute <br/>University of Missouri"
date: "<table style=\"border-style:none;padding-top:30px;\" class=\".table\">
  <tr>
    <th style=\"padding-right:75px!important\"><a href=\"https://twitter.com/kearneymw\"> <i class=\"fa fa-twitter\"></i> </a></th>
    <th style=\"padding-left:75px!important\"><a href=\"https://github.com/mkearney\"> <i class=\"fa fa-github\"></i> </a></th>
  </tr>
  <tr style=\"background-color:#fff\">
    <th style=\"padding-right:75px!important\"><a href=\"https://github.com/mkearney\"> @kearneymw </a></th>
    <th style=\"padding-left:75px!important\"><a href=\"https://github.com/mkearney\"> @mkearney </a></th>
  </tr></table>"
output:
  xaringan::moon_reader:
    lib_dir: 01-slides
    css: ["robot", "robot-fonts"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE,
  collapse = TRUE, comment = "#>")
options(htmltools.dir.version = FALSE)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```


## Scientific Method  
1. Research question
1. Theory development
1. Hypotheses
1. Design
1. **Analysis**

---

## What makes for an interesting question?  
- Politically important  
- Contribute to scientific understanding/literature  
- Personally interesting  
- Unresolved

---

## Three Types of Research Questions
- Prevalence
- Changes
- Causal Effects

---

## Causal Questions
- Forward causal questions
    - What effect(s) does X have?
    - ``What if?'' questions
- Backward causal questions
    - What causes Y?

---

## Why not backward causal questions?
- The set of potential X's is infinite
- We can only test a few at a time
- Some X's might be unobservable or unknown
- Showing that X1 causes Y doesn't tell us anything about whether X2 causes Y

---


## Concepts
- Conceptual (i.e., definition)
- Indicators (i.e., operationalization) 

---

## Evaluating Concepts
- Resonance: is it intuitive?
- Domain: where does it apply?
- Extension: how many referants?
- Fecundity: is it useful?
- Utility: can we observe it? how?

---

## Theory Development
- Caveat: Not the focus of this course
- Theories are arguments \textit{and} explanations
- Theories are causal in nature
- Often involve claims about mechanisms
- Rooted in past evidence or observation

---

## From Hypotheses to Design
- Hypothesis: Expectations about differences in outcomes across levels of a putatively causal variable
- Design: Selection and arrangement of evidence (Gerring 2012)
- Design must reveal evidence about our hypotheses
  - Selection of observations/units
  - Observation of outcome(s)
  - Observation of variation on the causal variable
  - Causal identification

---

## History
History of Political Science Methods

---

## Early methods
- Philosophy
- History
- Formal legalism

--

## Behavioral revolution (1950s)- 
Sample surveys
  - Basic quantitative methods

---

## Credibility revolution (1960s, 1980s, 2000s)- 
Matching
- Experiments
- Quasi-experiments (see Week 11)

---

## Post-positivists (21st century)- 
Qualitative and interpretive methods

---

## The Experimental Ideal
- Randomized experiment, or randomized control trial
- The observation of units after, and possibly before, a randomly assigned intervention in a controlled setting, which tests one or more precise causal expectations
- A correctly executed experiment always provides clear causal inference
- It solves both the temporal ordering and confounding problems
- Treatment (X) is applied by the researcher before outcome (Y)
- Randomization means there are no confounding (Z) variables

---

## Questions?

---

## Course Objectives
- Describe politically relevant research questions and hypotheses
- Evaluate and deduce observable implications from political science theories
    - Explain statistical procedures and their appropriate usages
- Apply statistical procedures to relevant research problems
- Synthesize results from statistical analyses into well-written and well-structured essays
- Demonstrate how to use Stata for statistical analysis

---

## Why Stata?
- SPSS is outdated
- SAS is too expensive (and too ugly)
- R is perceived as having a steep learning curve
- Stata is popular in political science and does everything we need

---

## Textbooks and Readings
- Everything else can be found online

---

## Exam
- 7-day written exam
- Answer 1 or 2 questions applying techniques learned in the course
- Choice of 2--3 research topics and datasets
- Write-up a mini research paper

---

## Four Assignments
- Required!
- Purpose- Practice techniques learned in the course- Receive feedback before the exam
- Schedule:- Essay 1 due February 27 to David % Something on OLS?- Essay 2 due March 20 to Thomas % Something on causality/research design?- Essay 3 due April 10 to David % Something on panel/multilevel?- Essay 4 due May 8 to Thomas % Something on GLM?
- On Blackboard about two weeks before deadline
- Submit via Blackboard

---

## Weekly Activities
- Lecture
- Partner/group activities
- Laboratory sessions

---

## Laboratory Sessions
- Hands-on practice with Stata
- Wednesday, 14:00--16:00
- Building/Room 1341-315

---

## Course Outline
- Research design (2 weeks)
- OLS Regression (2 weeks)
- Data handling (1 week)
- Causal inference (1 week)
- Panel and multi-level regression (2 weeks)
- GLMs (5 weeks)

---

## Instructor
- Office: Lee Hills Hall 314 
- Email: kearneymw@missouri.edu

---

## Introductions
- Please post an introduction on Blackboard
- Go to:  Materials from students >  Discussion Board >  The Facebook >  Introductions
- Post a photo and give us a short presentation of yourself



<style>
body {font-size: 20px;}
ul li {
margin-top: .75em;
margin-bottom: .75em;
}
</style>