---
title: "Day 1"
subtitle: "Quantitative research"
author: "Michael W. Kearney📊<br/>School of Journalism <br/>Informatics Institute <br/>University of Missouri"
date: "<table style=\"border-style:none;padding-top:30px;\" class=\".table\">
  <tr>
    <th style=\"padding-right:75px!important\"><a href=\"https://twitter.com/kearneymw\"> <i class=\"fa fa-twitter\"></i> </a></th>
    <th style=\"padding-left:75px!important\"><a href=\"https://github.com/mkearney\"> <i class=\"fa fa-github\"></i> </a></th>
  </tr>
  <tr style=\"background-color:#fff\">
    <th style=\"padding-right:75px!important\"><a href=\"https://github.com/mkearney\"> @kearneymw </a></th>
    <th style=\"padding-left:75px!important\"><a href=\"https://github.com/mkearney\"> @mkearney </a></th>
  </tr></table>"
output:
  xaringan::moon_reader:
    lib_dir: lib
    css: ["robot", "robot-fonts", "css/slides.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE,
  collapse = TRUE, comment = "#>")
options(htmltools.dir.version = FALSE)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```


## Quantitative research
+ Review scientific method
+ Revidw research design

---

## Scientific Method  
- Try to be "objective"
- Theories should be falsifiable
- Research should be reproducible
- Knowledge is cumulative and provisional


---

## Research questions
- Important to journalism/mass communication
- Contribute to scientific understanding/literature  
- Personally interesting  
- Unresolved or unknown

---

## Research designs
- Survey
- Experiment
- Content analysis

---

## Measuring constructs
- Conceptual (i.e., definition)
- Operational (i.e., indicators) 


---

## Hypotheses to design
- Hypothesis: Expectations of co-variations between two or more variables
- Design must test hypotheses
   - Unit of analysis
   - Observation of variables of interest
   - Observation of mechanisms/explanatory
   - Observation of other relevant or confounding variables

---

## Course Objectives
- Describe journalism/media relevant research questions and hypotheses
- Evaluate and deduce observable implications from mass media and journalism theories
    - Explain statistical procedures and their appropriate usages
- Apply statistical procedures to relevant research problems
- Synthesize results from statistical analyses into well-written and well-structured essays
- Demonstrate how to use R for statistical analysis

---

## Why R?
- SPSS/SAS/stata all cost money
- R is open source, free, and at cutting edge
- Learning R means learning programming (web scraping, automated work flows, etc.)

---

## Exams
- Two take-home exams
- Each exam should take anywhere from 2-5 hours
- More details as exams get clsoser

---

## Homework assignments
- Assignments/submissions on Canvas
- All assignments will require use of R

---

## Weekly Activities
- Various in-class activities

---

## Course Outline
- Research design
- Group comparisons
- Correlations and factors
- Linear models
- Advanced models
- Text analysis
- Data science

---

## Instructor
- Office: 
    - Lee Hills Hall 314 
    - Thursdays 11-2pm
- Email: kearneymw@missouri.edu


---

## Introductions
- Your full name
- Where you are in the program?
- What are your research interests?
- What stats courses have you taken?
- What do you hope to learn?



---
class: inverse, center, middle

# Quantitative research basics

---

## Defining variables

**Conceptual definition**

- A description of a variable's **theoretical** meaning.

**Operational definition**

- A description of a variable's **observable** meaning.

---

## Example

- Let's walk through an example of defining variable(s) and thinking about it in more practical terms

---

## Class size

Define the construct *class size*

- **Class size** refers to the...
    - Physical dimensions of the classroom
    - The number of students
    - The mass of the students

---

## Comparing classes sizes

Let's say we want to compare two observed class sizes

- **CLASS 1**: 30' x 30' room with 5 students weighing 1500 total lbs
- **CLASS 2**: 20' x 20' room with 10 students weighing 1250 total lbs

---

## Defining "class size"

- **CLASS 1**: 30' x 30' room with 5 students weighing 1500 total lbs
- **CLASS 2**: 20' x 20' room with 10 students weighing 1250 total lbs
- If we define class size **physical space**, class 1 is biggest
- If we define class size as **number of students**, class 2 is biggest
- If we define class size as **mass of students**, class 1 is biggest

Is any definition right or wrong?


---
class: inverse, center, middle

# Your turn

---

## Media exposure

- Conceptual definition:
- Operational definition:

---

## Views on climate change

- Conceptual definition:
- Operational definition:

---

## Coverage of environmental issues

- Conceptual definition:
- Operational definition:

---

## Accuracy in reporting

- Conceptual definition:
- Operational definition:

---

## Fake news

- Conceptual definition:
- Operational definition:


---

## Social media use

- Conceptual definition:
- Operational definition:


---

## Political ideology

- Conceptual definition:
- Operational definition:

---

## Perceived role of journalists

- Conceptual definition:
- Operational definition:

---

# IVs and DVs
class: inverse, center, middle

---

## Classifying variables

- Variables can be classified according to their status in a theoretical and/or statistical model
- There are several different labels applied toward this end, but for the most part they all do the same thing
    - Variables that represent the *cause*
    - Variables that represent the *effect*

---

## Terminology

- The cause is the **independent** variable
- The effect is the **dependent** variable
- There's also exogeneous and endogenous, predictors and outcomes, and probably some other synonyms

---

## Cause `!=` cause

- Although we use the cause/effect heuristic when modeling the relationship between two variables, we usually acknowledge multiple, reinforcing, or some underlying "root" causes
- As long as we all know that, the cause/effect heuristic is still helpful for organizing our theoretical and statistical models
    - Bad reporting of scientific research happens when we take cause/effect terminology too literally

---
class: inverse, center, middle

# Your turn

---

## IV or DV?

- Sun
- Surface temperature

---

## IV or DV?

- Reading
- Knowledge

---

## IV or DV?

- Public perceptions of an event
- Reporting information about an event

---

## Independent or dependent?

- Breakfast
- Health

---

## Independent or dependent?

- Exercise
- Health

---

## Independent or dependent?

- Social media
- Face-to-face interaction

---

# Hypotheses/research questions

---

## Relationships between variables

- Research questions ask about the relationship between two or more variables
    - These questions can guess direction (e.g., positive vs negative) but I think that kind of defeats the purpose
- Hypotheses predict the relationship between two or more variables
    - Hypotheses can either predict **whether** there is a relationship or what **direction** the relationship is in

> Hypotheses allow for more definitive inferences

---

## RQs/Hs

- Use **research questions** when there isn't a lot of research in an area and the theory isn't clear about what exactly to expect
- Otherwise, use **hypotheses**
